In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
%matplotlib inline
# Device configuration
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

In [2]:
train_data = pd.read_csv('/Users/JosephVele/Downloads/all/train_photo_to_biz_ids.csv')

In [3]:
class yelpTrainingDataset(torch.utils.data.Dataset):

    def __init__(self,text_file,root_dir,transform=transformMnistm):
        """
        Args:
            text_file(string): path to text file
            root_dir(string): directory with all train images
        """
        self.name_frame = pd.read_csv(text_file,sep=" ",usecols=range(1))
        self.label_frame = pd.read_csv(text_file,sep=" ",usecols=range(2,10))
        self.root_dir = root_dir
        self.transform = transform

    def __len__(self):
        return len(self.name_frame)

    def __getitem__(self, idx):
        img_name = os.path.join(self.root_dir, self.name_frame.iloc[idx, 0])
        image = Image.open(img_name)
        image = self.transform(image)
        labels = self.label_frame.iloc[idx, 0]
        #labels = labels.reshape(-1, 2)
        sample = {'image': image, 'labels': labels}

        return sample


mnistmTrainSet = yelpTrainingDataset(text_file ='/Users/JosephVele/Downloads/all/train_photo_to_biz_ids.csv',
                                   root_dir = '/Users/JosephVele/Downloads/all/train_photos')

mnistmTrainLoader = torch.utils.data.DataLoader(mnistmTrainSet,batch_size=16,shuffle=True, num_workers=2)

,photo_id,business_id,Label_0,Label_1,Label_2,Label_3,Label_4,Label_5,Label_6,Label_7,Label_8
0,204149,3034,0,0,0,1,0,0,0,0,1
1,52779,2805,0,1,1,1,0,1,1,1,0
2,278973,485,0,1,1,1,1,1,1,1,0
3,195284,485,0,1,1,1,1,1,1,1,0
4,19992,485,0,1,1,1,1,1,1,1,0
5,80748,485,0,1,1,1,1,1,1,1,0
6,444996,1783,0,1,1,1,0,1,1,1,0
7,200285,35,0,1,1,0,0,1,1,0,1
8,90572,35,0,1,1,0,0,1,1,0,1
9,27565,1313,0,0,0,1,0,0,1,0,1
10,228371,1313,0,0,0,1,0,0,1,0,1
11,166925,2787,0,0,0,1,0,1,0,0,1
12,310868,3216,0,1,0,0,0,1,1,1,0
13,13318,3385,0,0,1,0,1,1,1,0,0
14,290904,2896,0,0,0,1,0,0,1,0,1
15,71940,1193,0,1,1,0,0,1,1,0,0
16,211449,1193,0,1,1,0,0,1,1,0,0
17,368909,1193,0,1,1,0,0,1,1,0,0
18,118126,1193,0,1,1,0,0,1,1,0,0
19,188137,3703,0,0,0,1,0,0,0,0,1
20,12355,3703,0,0,0,1,0,0,0,0,1
21,232115,3703,0,0,0,1,0,0,0,0,1
22,208176,3703,0,0,0,1,0,0,0,0,1
23,362562,3909,1,1,0,0,0,0,0,0,1
24,244500,3909,1,1,0,0,0,0,0,0,1
25,18589,245,0,1,1,1,1,1,1,1,1
26,186937,1605,0,1,0,0,0,0,0,0,1
27,14826,2997,0,0,1,0,0,1,1,0,1
28,156728,3735,0,0,0,0,0,1,1,0,1
29,444034,818,1,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
234812,329129,3574,0,1,1,1,0,1,1,0,1
234813,453473,3574,0,1,1,1,0,1,1,0,1
234814,75548,3574,0,1,1,1,0,1,1,0,1
234815,63540,3574,0,1,1,1,0,1,1,0,1
234816,17333,3574,0,1,1,1,0,1,1,0,1
234817,256794,3574,0,1,1,1,0,1,1,0,1
234818,236728,3574,0,1,1,1,0,1,1,0,1
234819,357535,3574,0,1,1,1,0,1,1,0,1
234820,389287,487,0,1,1,1,1,1,1,0,0
234821,200892,119,0,1,1,0,1,1,1,1,0
234822,30428,1129,0,0,0,0,0,0,1,0,1
234823,256780,3101,1,0,0,1,0,0,0,0,1
234824,180237,3101,1,0,0,1,0,0,0,0,1
234825,252330,3101,1,0,0,1,0,0,0,0,1
234826,27701,3101,1,0,0,1,0,0,0,0,1
234827,464838,1246,0,0,1,0,0,1,1,0,0
234828,330346,1773,0,1,1,1,1,1,1,1,0
234829,374143,1773,0,1,1,1,1,1,1,1,0
234830,264826,1773,0,1,1,1,1,1,1,1,0
234831,416194,3160,1,1,1,0,0,0,1,0,1
234832,381557,3160,1,1,1,0,0,0,1,0,1
234833,225446,3160,1,1,1,0,0,0,1,0,1
234834,414969,3160,1,1,1,0,0,0,1,0,1
234835,27909,496,0,1,0,0,1,1,1,1,0
234836,356345,496,0,1,0,0,1,1,1,1,0
234837,325414,496,0,1,0,0,1,1,1,1,0
234838,301030,3565,0,1,1,0,0,1,1,0,0
234839,355839,1875,0,1,1,0,0,1,1,1,1
234840,20474,3888,1,1,1,1,0,1,1,1,1
234841,263884,3888,1,1,1,1,0,1,1,1,1